services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: techquiz_app
    ports:
      - "8000:8000"    # container:host
    volumes:
      - .:/var/www
    environment:
      APP_ENV: local
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/database/database.sqlite