
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./:/var/www:cached
      - laravel_framework_cache:/var/www/storage/framework/cache
      - laravel_framework_sessions:/var/www/storage/framework/sessions
      - laravel_framework_views:/var/www/storage/framework/views
      - laravel_logs:/var/www/storage/logs
      - laravel_bootstrap_cache:/var/www/bootstrap/cache
    networks:
      - laravel

  webserver:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www:cached
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:

volumes:
  laravel_framework_cache:
  laravel_framework_sessions:
  laravel_framework_views:
  laravel_logs:
  laravel_bootstrap_cache:
